const nodemailer = require("nodemailer");

/**
 * Send the AI-generated summary to the recipient via SMTP.
 */
async function sendEmail(to, summary) {
  const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST || "smtp.gmail.com",
    port: parseInt(process.env.SMTP_PORT) || 587,
    secure: false,
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });

  // Convert markdown-style bold to HTML bold for nicer emails
  const htmlBody = summary
    .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
    .replace(/\n/g, "<br>");

  const mailOptions = {
    from: `"Sales Insight Automator" <${process.env.EMAIL_FROM || process.env.SMTP_USER}>`,
    to,
    subject: "📊 Your AI-Generated Sales Summary — Rabbitt AI",
    text: summary,
    html: `
      <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 680px; margin: auto; padding: 24px; color: #1a1a2e;">
        <div style="background: linear-gradient(135deg, #6c63ff 0%, #3b82f6 100%); border-radius: 12px 12px 0 0; padding: 28px; text-align: center;">
          <h1 style="color: #fff; margin: 0; font-size: 22px;">📊 Sales Insight Report</h1>
          <p style="color: #e0e7ff; margin: 6px 0 0; font-size: 14px;">Auto-generated by Rabbitt AI</p>
        </div>
        <div style="background: #ffffff; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 12px 12px; padding: 28px; line-height: 1.7; font-size: 15px;">
          ${htmlBody}
        </div>
        <p style="text-align: center; font-size: 12px; color: #9ca3af; margin-top: 20px;">
          Powered by Sales Insight Automator &bull; Rabbitt AI
        </p>
      </div>
    `,
  };

  await transporter.sendMail(mailOptions);
}

module.exports = { sendEmail };
